# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2babd7878bdc4966465815c239431277db6c4e1eb92b0e3d792028f617397ffcec3144b7cbbad04fe5a08f5834db5425d5e9cd4c26ba949e4840ddcb8bbb7e07

test:
  secret_key_base: 72fc98acb16a5836807a9615c66fa854b5034d6e7c531a5aa0910e8be0a7f644d50c9adf61bfd3ee0e848b5198beb2c5cb13e4a534d4fbc0c5980387660a94c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
